name: pull request

on:
  pull_request:
  merge_group:

permissions:
  actions: read
  contents: read
  pull-requests: read

concurrency: pull-request-${{ github.event.pull_request.number }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: pnpm/action-setup@v6

      - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="test"

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'

      - run: pnpm install

      - uses: nrwl/nx-set-shas@v5

      - run: pnpm exec nx affected -t lint build

      - run: pnpm exec nx test core
